### ISSUE TITLE
Implementar testes unitários

### ISSUE THREAD

**Issue by AbnerErnaniADSFatec** [ProjetoIntegradorADSFatec/api-restful#28]
Rotina de testes com o JUnit

**Comment by GomesDosSantos** [comment]
Pull Request já disponível: https://github.com/ProjetoIntegradorADSFatec/api-restful/pull/36

**Comment by GomesDosSantos** [comment]
@AbnerErnaniADSFatec    
 Eu também acho interessante começarmos a colocar tags nos repositórios. Desta forma fica mais fácil retornar à versões anteriores do projeto ou observar as mudanças essenciais a cada entrega.     
O processo de criação delas é bem simples:
`git tag -a <nome_da_tag> -m "descrição"`      
e depois para enviar para o repositório:   
`git push --tags`    
      
[Fonte](https://git-scm.com/book/en/v2/Git-Basics-Tagging)
