### ISSUE TITLE
Criação e gerenciamento de um sistema de tags

### ISSUE THREAD

**Issue by AbnerErnaniADSFatec** [ProjetoIntegradorADSFatec/api-restful#37]
Criar um sistema de tags para o controle de versões anteriores do código.

**Comment by GomesDosSantos** [comment]
Não é possível passar as tags por pull request. [Por que não?](https://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request)    
Então elas devem ser adicionadas neste repositório quando necessário. [Tutorial](https://git-scm.com/book/en/v2/Git-Basics-Tagging)    
Após isso é possível referenciar o commit que possui a tag, reverter código ou testar entregas anteriores.
